### ISSUE TITLE
What are all the possible state changes?

### ISSUE THREAD

**Issue by DesignerTies** [jishi/node-sonos-discovery#119]
Thanks for this project, I'm having a lot of fun with it and it's super useful!
However I was wondering if there were any other state changes than 'volume-change', 'topology-change', 'transport-state' and 'mute-change'? For example a change on skipping a song or playing a new song. Thanks

**Comment by jishi** [comment]
Okay, lets see, it was a long time ago I touched this :)

So, I believe that changing song would always trigger a transport-state change, but it is also periodically about every 15 seconds (since that is how often it internally syncs the time elapsed value).

In addition to the once you mentioned, there is also queue-change, volume-change and mute-change

Not all of them are emitted via SonosSystem instance, some are Player instance only.

If you search for the .emit() calls in Player.js and SonosSystem.js you would find all of them.

**Comment by DesignerTies** [comment]
Thanks for your anwser! I got it now.
