### ISSUE TITLE
Enqueueing a track from streaming service (eg Rdio or Soundcloud)

### ISSUE THREAD

**Issue by dgmltn** [jishi/node-sonos-discovery#29]
I've tried AddURIToQueue to enqueue url's that look like this:

    uri: "x-sonos-http:_t%3a%3a1157781.mp3?sid=11&flags=32&sn=6",

The speaker returns a 500 error, and the Sonos Controller tells me, "Access Denied" (though the track information actually was added to the queue). I'm thinking this is a security issue from Sonos, but is there a way to solve it?

**Comment by jishi** [comment]
Hi Doug.

This is probably because these uris require the appropriate metadata as
well, which is different for each service. This metadata seem to be used as
a reference for fetching the appropriate data from said service like title,
albumart etc.

Do you send any metadata? Usually these calls work anyway, but it usually
lacks info in the queue listing and when playing it usually only says the
uri.

**Comment by dgmltn** [comment]
I've tried that, though perhaps my xml encoding wasn't perfect. I'll look more into that. Thanks!

**Comment by dgmltn** [comment]
Escaping the "&" in that url (along with escaping the entire metadata) seemed to help. Though I still have random "access denied" errors sometimes (even with the same request as one that worked one minute ago).

**Comment by jishi** [comment]
Hm, that's weird, since it will do that automatically:

  uri = uri != null ? xmlEntities.encode(uri) : "";
  metaData = metaData != null ? xmlEntities.encode(metaData) : "";

I usually make a wireshark dump of the request from the Sonos Controller and compare with my request to identify differences, then it usually becomes evident very fast on what the culprit is.
