### ISSUE TITLE
Sonos Music Service API

### ISSUE THREAD

**Issue by ColdFireIce** [jishi/node-sonos-discovery#74]
Hi,

I stumbled across this one: https://en.community.sonos.com/advanced-setups-229000/how-to-get-basic-information-about-music-services-31678/index2.html

Do you have any new information about using a central api to query all configured music services?
How would that work? What are the current problems?

Greetings

**Comment by jishi** [comment]
No, unfortunately not. The issue is that the credentials required for communicating with the central API is encrypted and I have yet to figure out how to decrypt those. For most services it is basically just a token that has been created during signup of the service (and renewed occasionally) but without the token, you don't have access to the api.
