### ISSUE TITLE
Change events for playlist changes

### ISSUE THREAD

**Issue by ColdFireIce** [jishi/node-sonos-discovery#75]
Hi,

I'm about to implement the playlist change emitter (queue-change, favorites-change and add playlists-change). I would report the uuid of the player when queue changes but, for favorites and playlists it concerns the whole system.
Is there anything against just passing this event through? Did you have other plans?

**Comment by ColdFireIce** [comment]
On this count, one more question: Do you have a list what the List identifiers stand for?
R:0,3,FV:2,3,FV:3,3...
I know FV:2 is the favorites Q:0 the player queue and SQ: are the saved playlists, but what are all the other lists? and is the value after the comma a couter or something else?

**Comment by jishi** [comment]
The queue/favorites/playlists change is merely a notification that anyone relying on those to be rendered, need to update them. This is not used in the http-api, but was used in the web-controller. Seems fine to just send them empty. What might be even easier might be to have a single notification, that can contain info about what has actually updated since that is probably evented at the same time from Sonos. something like:

"content-change" even emits: 
```
{
  "playlists": true,
  "favorites": true,
  "queue": false
}
```

or something.

The only list identifiers that I have identified is the ones that you mention. I do know that FV:3 is some sort of non-implemented preset functionality, and the same method is used for browsing the library. What I mention in this issue https://github.com/jishi/node-sonos-discovery/issues/7 is basically what I know.

**Comment by ColdFireIce** [comment]
so, you're also in the dark about what this comma separated value is?
The Problem is, that I have to subscribe an every player to the event, to get the queue-change event, but that also triggers a favorite- or playlists-change on every player... that not ideal...

**Comment by jishi** [comment]
Are you saying that the ContainerID always include all those IDs? You always get an event when you subscribe, and also on every re-subscribe so there will always be some unnecessary talk on the wire, but if it is only every few minutes I think it's fine. 

But with that said, for some events (favorites, playlists) it might make sense to aggregate notification that comes within a small timeframe and only event once.

**Comment by ColdFireIce** [comment]
No, the contained IDs vary. But I have to subscribe to every players ContentDirectory/Event to geht the queue change event. But this also means that every time the favorites/playlists change, all player send me a notification about that. so 6 speakers -> 6 events. that what I should try to catch and prevent.
The thing is, that these events contain the same payload like
```SQ:,9``` or ```FV:2,12```
the value after the comma seam to increase with every change: ```FV:2,13```
This would make it easy to filter the duplicate events. But I'm not sure if this is really consistent.

**Comment by jishi** [comment]
I don't know what the value after the comma means, haven't noticed it before. 

I would suggest that you handle playlist/favorites events from SonosSystem only (but you could let Player actually subscribe to it) that way you could filter out events based on which player you are subscribing to topology for (I don't think I store a UUID for it today, but that could be easily added). 

So maybe differentiate between queue-change, and playlist/favorite-change only?

**Comment by jishi** [comment]
I usually prevent duplicates by having a short timer delay which gets reset on each subsequent notification. Once it slows down, it would trigger the event.

**Comment by ColdFireIce** [comment]
I ran into a trade off problem here:
- using only one player: if this player drops out (gets disconnected), there would be no more list updates. What happens if this is the player that the SonosSystem subscribes to? There will be no `zonegroupstate` event, right? so shouldn't the `ZoneGroupTopology/Event` be subscribed on all players?
- using all players: what happens if 2 updates occure with little time between them? Using a timer and sending only the 1st update makes the library more responsive, as the event is emitted as soon as the 1st player sends an update. But that could also cause the 2nd real update to get swallowed.
If you use a timeout to send the event, the responsiveness gets lost, but no updates get swallowed.
- how long should the timeout be?

**Comment by jishi** [comment]
I have tested both approaches and using only one player causes less stress
for the system. I haven't fixed any reconnection logic for the topology
yet, since this is an uncommon thing and a restart fixes it, but sure, it
would be an improvement.

It should atleast handle it during resubscripotion, where a connection
error should trigger a fail over to another player, but as I said, it
should be generic for all global events (like topology anf similar)

**Comment by ColdFireIce** [comment]
Well the stress to the system can't really be reduced, as You have to subscribe to every single player, to get the queue update. The only thing is, that the notification handler can filter the events and not let the sonosSystem filter them. so there would be less event emitter communication between notification handler and sonosSystem. But the Events from the Player would still be received.

**Comment by ColdFireIce** [comment]
I think I managed it. See #86
