### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by ColdFireIce** [jishi/node-sonos-discovery#87]
Hi,

Why are you not publishing on npm?

Greetings

**Comment by GermanBluefox** [comment]
I must say even more, if he will not do that. I will make it and give him
the rights.
Because last change with static port 8083 broke my connection and to avoid
it at least npm release would be nice.
Very cool project, but static port should be removed.

Greetings,
Bluefox
7 Июл 2016 г. 15:42 пользователь "Daniel Becker" <notifications@github.com>
написал:

**Comment by GermanBluefox** [comment]
Ok I mean port 8080.
7 Июл 2016 г. 18:27 пользователь "Bluefox Fox" <dogafox@googlemail.com>
написал:

**Comment by ColdFireIce** [comment]
What static port? The current version trys to find an unused Port on the System for the Event-Callbacks, and on Sonos-Systems, its always :1400

**Comment by jishi** [comment]
The static port relates to the web-controller, not discovery. 

The reason for not publishing on npm has been that I can not guarantee support nor updates to it, and I personally find it highly annoying when people publish crap on public repositories that gets abandoned within months :) I didn't want to be equally bad.

I however have considered publishing the new version, but only the discovery library (I don't think npm is the place for actual applications), if I can iron out all quirks and also be more strict in my versioning and keeping backward compatibility.
